import 'package:powersync/powersync.dart';

/// PowerSync schema definition for Workouts.
/// This mirrors the Postgres schema and defines what syncs to devices.
/// Note: PowerSync automatically adds an 'id' column to each table.
const schema = Schema([
  Table('exercises', [
    Column.text('name'),
    Column.text('modality'),
    Column.text('equipment'),
    Column.text('cues'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('workout_templates', [
    Column.text('name'),
    Column.text('goal'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('workout_blocks', [
    Column.text('template_id'),
    Column.integer('block_index'),
    Column.text('type'),
    Column.text('title'),
    Column.integer('target_duration_seconds'),
    Column.text('description'),
    Column.integer('rounds'),
  ]),
  Table('workout_block_exercises', [
    Column.text('block_id'),
    Column.text('exercise_id'),
    Column.integer('exercise_index'),
    Column.text('prescription'),
    Column.integer('setup_duration_seconds'),
    Column.integer('work_duration_seconds'),
    Column.integer('rest_duration_seconds'),
  ]),
  Table('sessions', [
    Column.text('template_id'),
    Column.text('started_at'),
    Column.text('completed_at'),
    Column.integer('duration_seconds'),
    Column.text('notes'),
    Column.text('paused_at'),
    Column.integer('total_paused_duration_seconds'),
    Column.integer('average_heart_rate'),
    Column.integer('max_heart_rate'),
    Column.text('updated_at'),
  ]),
  Table('session_blocks', [
    Column.text('session_id'),
    Column.integer('block_index'),
    Column.text('type'),
    Column.integer('target_duration_seconds'),
    Column.integer('actual_duration_seconds'),
    Column.text('notes'),
    Column.integer('round_index'),
    Column.integer('total_rounds'),
  ]),
  Table('session_block_exercises', [
    Column.text('block_id'),
    Column.text('exercise_id'),
    Column.integer('exercise_index'),
    Column.text('prescription'),
    Column.integer('setup_duration_seconds'),
    Column.integer('work_duration_seconds'),
    Column.integer('rest_duration_seconds'),
  ]),
  Table('session_set_logs', [
    Column.text('block_id'),
    Column.text('exercise_id'),
    Column.integer('set_index'),
    Column.real('weight_kg'),
    Column.integer('reps'),
    Column.integer('duration_seconds'),
    Column.integer('unit_remaining'),
  ]),
  Table('fitness_goals', [
    Column.text('title'),
    Column.text('description'),
    Column.text('category'),
    Column.integer('priority'),
    Column.text('target_date'),
    Column.text('status'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('background_notes', [
    Column.text('goal_id'),
    Column.text('category'),
    Column.text('content'),
    Column.integer('is_active'),
    Column.text('source'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('session_notes', [
    Column.text('session_id'),
    Column.text('exercise_id'),
    Column.text('block_id'),
    Column.text('content'),
    Column.text('note_type'),
    Column.text('source'),
    Column.text('timestamp'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('heart_rate_samples', [
    Column.text('session_id'),
    Column.text('timestamp'),
    Column.integer('bpm'),
    Column.text('source'),
    Column.real('energy_kcal'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('training_influences', [
    Column.text('name'),
    Column.text('description'),
    Column.text('principles'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('runs', [
    Column.text('external_workout_id'),
    Column.text('started_at'),
    Column.text('ended_at'),
    Column.integer('duration_seconds'),
    Column.real('distance_meters'),
    Column.real('energy_kcal'),
    Column.real('avg_heart_rate_bpm'),
    Column.real('max_heart_rate_bpm'),
    Column.integer('is_indoor'),
    Column.integer('route_available'),
    Column.text('source_name'),
    Column.text('source_bundle_id'),
    Column.text('device_model'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('run_route_points', [
    Column.text('run_id'),
    Column.integer('point_index'),
    Column.real('lat'),
    Column.real('lng'),
    Column.real('altitude_meters'),
    Column.text('timestamp'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('run_heart_rate_samples', [
    Column.text('run_id'),
    Column.text('timestamp'),
    Column.integer('bpm'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table.localOnly('run_computed_metrics', [
    Column.integer('zone2_seconds'),
    Column.real('trimp'),
    Column.integer('has_hr_samples'),
    Column.integer('zone2_hr_lower'),
    Column.integer('zone2_hr_upper'),
    Column.integer('resting_hr'),
    Column.text('computed_at'),
  ]),

  Table.localOnly('session_computed_metrics', [
    Column.integer('zone2_seconds'),
    Column.real('trimp'),
    Column.integer('has_hr_samples'),
    Column.integer('zone2_hr_lower'),
    Column.integer('zone2_hr_upper'),
    Column.integer('resting_hr'),
    Column.text('computed_at'),
  ]),
]);
